version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks: 
      - tronvolution-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tronvolutionwebsite.rule=Host(`tronvolution.com`) || Host(`www.tronvolution.com`)"
      - "traefik.http.routers.tronvolutionwebsite.entrypoints=https"
      - "traefik.http.routers.tronvolutionwebsite.tls=true"
      - "traefik.http.routers.tronvolutionwebsite.tls.certresolver=letsencrypt"
      - "traefik.http.services.tronvolutionwebsite.loadbalancer.server.port=80"
      # http -> https rerouting
      - "traefik.http.routers.tronvolutionwebsite-http.rule=Host(`tronvolution.com`) || Host(`www.tronvolution.com`)"
      - "traefik.http.routers.tronvolutionwebsite-http.entrypoints=http"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.tronvolutionwebsite-http.middlewares=https-redirect"
      # Add middleware for SPA
      - "traefik.http.middlewares.spa-middleware.replacepathregex.regex=^(/[^\\.]*)$$"
      - "traefik.http.middlewares.spa-middleware.replacepathregex.replacement=/index.html"
      - "traefik.http.routers.tronvolutionwebsite.middlewares=spa-middleware"
    






networks:
  tronvolution-network:
    driver: bridge
    name: tronvolution-network
    external: true
